#!/bin/bash -eu

cd $(dirname "${0}")
export DOTFILES_ROOT=$(pwd -P)

echo "${DOTFILES_ROOT}" >${HOME}/.dotfiles_root

. ${DOTFILES_ROOT}/lib/os.sh

if test ${OS} = "macos"; then
  . ${DOTFILES_ROOT}/lib/install_brew.sh
  . ${DOTFILES_ROOT}/lib/brew_path.sh
fi

if test ${OS} = "linux"; then
  sudo apt update -y
  sudo apt upgrade -y
fi

. ${DOTFILES_ROOT}/mise/setup.sh
. ${DOTFILES_ROOT}/ruby/setup.sh

ruby ${DOTFILES_ROOT}/src/bootstrap.rb
