git:
  paging:
    colorArg: always
    pager: delta --paging=never

# Disable the prompt when open a file with editor.
promptToReturnFromSubprocess: false
os:
  editPreset: nvim-remote

# snacks.vim will use q to quit lazygit.
# keybinding:
#   universal:
#     # Do not use q to quit.
#     # I want to use q to return.
#     # But it is not possible return from input mode.
#     quit: ""

gui:
  mouseEvents: false
