git:
  paging:
    colorArg: always
    pager: delta --paging=never
# Disable the prompt when open a file with editor.
promptToReturnFromSubprocess: false
os:
  edit: "zed {{filename}}"
  editAtLine: "zed {{filename}}:{{line}}"
  editAtLineAndWait: "zed --wait {{filename}}:{{line}}"
